### ISSUE TITLE
感觉是个很牛逼的开源，但是怎么用呢 ？怎么编译？linux

### ISSUE THREAD

**Issue by szhansen** [ireader/sdk#1]

**Comment by ireader** [comment]
libhttp/libaio目录下有Makefile文件，直接执行make即可。 
如果提示gccrule.sh/svnver.sh没有执行权限，请加上chmod +x gccrule.sh。

其它sdk/source目录下的文件直接加到exe项目中编译。
特别注意thread-pool.c/aio-socket-epoll.c/app-log.c等文件包含全局静态变量，只能包含在一个so或exe项目中。
