### ISSUE TITLE
ice-agent-test.cpp demo发送数据不成功

### ISSUE THREAD

**Issue by zhaotao6584851** [ireader/sdk#11]
host, srflx, relay这些地址都可以获取到了，按照demo做了，数据发送不成功。
demo效果是和libnice是一样的效果吧，libnice双方发送数据都可以通。
这个demo始终想对方发送数据失败，对方收不到数据

**Comment by ireader** [comment]
请在两台电脑上用wireshark分别抓包，把抓包文件贴一下。

然后请简单描述下网络环境，机器ip。

**Comment by zhaotao6584851** [comment]
星期一我把测试的代码发给你，我也是在同一台电脑上试的，我没具体分析代码。我发现一端发送数据是可以的，另一段是不行的走的是relay，而且stun数据不对，直接收到的就是没有stun头的信息，具体我发你测试代码。我也是对ice比较感兴趣学习学习。





------------------ 原始邮件 ------------------
发件人: Chen <notifications@github.com&gt;
发送时间: 2020年5月16日 19:17
收件人: ireader/sdk <sdk@noreply.github.com&gt;
抄送: zhaotao6584851 <244054934@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
请在两台电脑上用wireshark分别抓包，把抓包文件贴一下。
 
然后请简单描述下网络环境，机器ip。

**Comment by zhaotao6584851** [comment]
我在一台电脑上ice测试，里面有抓包的东西，我在stun-agent.c里加了一个打印的



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上7:17
收件人:&nbsp;"ireader/sdk"<sdk@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
请在两台电脑上用wireshark分别抓包，把抓包文件贴一下。
 
然后请简单描述下网络环境，机器ip。

**Comment by ireader** [comment]
日志及抓包文件呢？

**Comment by zhaotao6584851** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上8:12
收件人:&nbsp;"ireader/sdk"<sdk@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
日志及抓包文件呢？

**Comment by ireader** [comment]
是不是附件没有发出来？

**Comment by zhaotao6584851** [comment]
附件收到了吧，有结果没有？





------------------ 原始邮件 ------------------
发件人: Chen <notifications@github.com&gt;
发送时间: 2020年5月22日 09:11
收件人: ireader/sdk <sdk@noreply.github.com&gt;
抄送: zhaotao6584851 <244054934@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
是不是附件没有发出来？

**Comment by ireader** [comment]
没有收到附件

**Comment by zhaotao6584851** [comment]
&nbsp;这个有附件



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 下午5:15
收件人:&nbsp;"ireader/sdk"<sdk@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
没有收到附件
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

ice-demo.7z (270.3K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7938636298f4ce9bafc3e86c1332074b090c050750540d5d145c5301511f01560e0d4e03505407490e595655070700050e0b51533539350d5a5d4e06505f5a4a0e42635f&t=exs_ftn_download&code=98cb525d

**Comment by ireader** [comment]
已收到附件，感谢！

**Comment by ireader** [comment]
问题已定位，是查找pair时出错导致，修改代码如下：

libice/src/ice-candidates.h文件：
```
static inline int ice_candidate_pair_compare_addr(const struct ice_candidate_pair_t* pair, const struct stun_address_t* addr)
{
	if (0 == socket_addr_compare((const struct sockaddr*) & pair->local.host, (const struct sockaddr*) & addr->host)
		&& 0 == socket_addr_compare((const struct sockaddr*) & pair->remote.host, (const struct sockaddr*) & addr->peer)
		&& (ICE_CANDIDATE_RELAYED != pair->local.type || 0 == socket_addr_compare((const struct sockaddr*) & pair->local.addr, (const struct sockaddr*)&addr->relay)))
	{
		return 0;
	}
	return -1;
}
```

**Comment by zhaotao6584851** [comment]
好的 &nbsp;谢谢你了 晚上我在试下





------------------ 原始邮件 ------------------
发件人: Chen <notifications@github.com&gt;
发送时间: 2020年6月10日 13:35
收件人: ireader/sdk <sdk@noreply.github.com&gt;
抄送: zhaotao6584851 <244054934@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
问题已定位，是查找pair时出错导致，修改代码如下：
 
libice/src/ice-candidates.h文件：
 static inline int ice_candidate_pair_compare_addr(const struct ice_candidate_pair_t* pair, const struct stun_address_t* addr) { if (0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;local.host, (const struct sockaddr*) &amp; addr-&gt;host) &amp;&amp; 0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;remote.host, (const struct sockaddr*) &amp; addr-&gt;peer) &amp;&amp; (ICE_CANDIDATE_RELAYED != pair-&gt;local.type || 0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;local.addr, (const struct sockaddr*)&amp;addr-&gt;relay))) { return 0; } return -1; }

**Comment by zhaotao6584851** [comment]
我刚试了下 发现一个问题了
一个线程接受数据然后调用ice_agent_input 之后会回调ice_agent_test_ondata 打印数据
但是我测试发现一直没有触发ice_agent_test_ondata这个函数
反而调用ice_agent_input之前打印就是我收的数据了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 中午1:35
收件人:&nbsp;"ireader/sdk"<sdk@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/sdk] ice-agent-test.cpp demo发送数据不成功 (#11)





 
问题已定位，是查找pair时出错导致，修改代码如下：
 
libice/src/ice-candidates.h文件：
 static inline int ice_candidate_pair_compare_addr(const struct ice_candidate_pair_t* pair, const struct stun_address_t* addr) { 	if (0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;local.host, (const struct sockaddr*) &amp; addr-&gt;host) 		&amp;&amp; 0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;remote.host, (const struct sockaddr*) &amp; addr-&gt;peer) 		&amp;&amp; (ICE_CANDIDATE_RELAYED != pair-&gt;local.type || 0 == socket_addr_compare((const struct sockaddr*) &amp; pair-&gt;local.addr, (const struct sockaddr*)&amp;addr-&gt;relay))) 	{ 		return 0; 	} 	return -1; }

**Comment by ireader** [comment]
在非relay情况下，发送的数据就是原始数据，这是正常的。
> 反而调用ice_agent_input之前打印就是我收的数据了

stun对数据包有要求，一般只用来传RTP包(stun-agent.c:417)
普通数据传输方面还有点问题，主要是需要区分普通数据包和stun数据包。
> 一个线程接受数据然后调用ice_agent_input 之后会回调ice_agent_test_ondata 打印数据
> 但是我测试发现一直没有触发ice_agent_test_ondata这个函数
