### ISSUE TITLE
'ip_route_get' error if 'destination' is loopback address 

### ISSUE THREAD

**Issue by chenbd** [ireader/sdk#12]
eg: when ' ::ffff:127.0.0.1' used as input, the out parameter 'ip' not filled.

**Comment by ireader** [comment]
linux ip_route_get filter loopback address.

You can change code like this:

sdk/source/port/route-netlink.h: 148
`if (rt->rtm_table != RT_TABLE_MAIN)`
==>
`if (rt->rtm_table != RT_TABLE_MAIN && rt->rtm_table != RT_TABLE_LOCAL && rt->rtm_table != RT_TABLE_DEFAULT)`

and sdk/source/port/route-netlink.h: 242
`if (ifa->ifa_scope != RT_SCOPE_UNIVERSE)`
==>
`if (ifa->ifa_scope != RT_SCOPE_UNIVERSE && ifa->ifa_scope != RT_SCOPE_HOST)`
