### ISSUE TITLE
base64解码函数输出不正确

### ISSUE THREAD

**Issue by joyouswind** [ireader/sdk#14]
使用base64_decode函数解码，cnRzcDovL2FkbWluOkhLMTIzNDU2QDE5Mi4xNjguMTUwLjg4OjU1NC9oMjY0LzAvbWFpbi9hdl9zdHJlYW0被解码为rtsp://admin:HK123456@192.168.150.88:554/h264/0/main/av_stre，缺少两个字节，使用ffmpeg的av_base64_decode函数，解码正确。

**Comment by ireader** [comment]
查了下是base64_decode兼容的问题。 目前需要在后面价加个=号才能解出来：“cnRzcDovL2FkbWluOkhLMTIzNDU2QDE5Mi4xNjguMTUwLjg4OjU1NC9oMjY0LzAvbWFpbi9hdl9zdHJlYW0=”。

周末解决这个bug。
