### ISSUE TITLE
make: *** 没有规则可以创建“debug.linux/libaio.so”需要的目标“../source/timer.o”。 停止。

### ISSUE THREAD

**Issue by jingith** [ireader/sdk#3]
make -C sdk/libaio && make -C sdk/libhttp && make -C media-server/libmpeg && make -C media-server/libflv && make -C media-server/libhls

make: *** 没有规则可以创建“debug.linux/libaio.so”需要的目标“../source/timer.o”。 停止。

**Comment by ireader** [comment]
update
