### ISSUE TITLE
unknown type name ‘IN6_ADDR’

### ISSUE THREAD

**Issue by zhenghr2021** [ireader/sdk#39]
../include/sys/sock.h:196:62: error: unknown type name ‘IN6_ADDR’
 static inline int socket_ipv6_netmask(IN uint8_t prefix, OUT IN6_ADDR* addr);

**Comment by zhenghr2021** [comment]
make err

**Comment by zhenghr2021** [comment]
使用gcc 4.8.5 系统centos7

**Comment by ireader** [comment]
代码提交有问题，先做些修改：
IN_ADDR 替换为 struct in_addr
IN6_ADDR 替换为 struct in6_addr
