### ISSUE TITLE
qq群不能使用了？

### ISSUE THREAD

**Issue by Ghazigq** [ireader/sdk#51]
我想增加rtos的代码，比如freertos rtthread或者其他pr，提交前想先交流下，有群或者联系方式吗？

**Comment by ireader** [comment]
可以加QQ群：714822684

**Comment by Ghazigq** [comment]
> 714822684
![image](https://github.com/user-attachments/assets/fb1978be-dc36-4027-8da4-7ab24608a1cb)

**Comment by Ghazigq** [comment]
找不到群呀 @ireader

**Comment by ireader** [comment]
把你qq号发到邮箱，我直接拉你？

**Comment by Ghazigq** [comment]
> 把你qq号发到邮箱，我直接拉你？

已发送邮件到你的邮箱
