### ISSUE TITLE
希望 libhttp 能够增加服务端 multipart/upload 的例程，谢谢！

### ISSUE THREAD

**Issue by hug2008** [ireader/sdk#6]

**Comment by ireader** [comment]
multipart/upload ??? 是指multipart/form-data吗？ 
1. http服务端接收客户端请求， 判断Content-Type是否multipart/form-data
2. 调用http_get_upload_boundary获取boundary字符串
3. 调用http_get_upload_data获取解析收的数据。

**Comment by hug2008** [comment]
是的，谢谢指点
